#!/usr/bin/env python3
###
# This file is a part of the NVDA project.
# URL: http://www.nvaccess.org/
# Copyright 2016-2024 NV Access Limited, Leonard de Ruijter
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2.0, as published by
# the Free Software Foundation.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# This license can be found at:
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
###

Import(
	"env",
	"sourceDir",
	"localLib",
	"uwpOcrStaticLib",
)


# Ignoring Flake8 F821: 'undefined name' due to nonstandard SCons import
env = env.Clone()  # noqa: F821

source = [
	env["projectResFile"],
	"oneCoreSpeech.cpp",
]
libs = [
	"WindowsApp",
	# Ignoring Flake8 F821: 'undefined name' due to nonstandard SCons import
	localLib[2],  # noqa: F821
]
# uwpOcr.cpp was ported to the nvda_uwp_ocr Rust crate; link its staticlib +
# the system libs the Rust std / windows-core runtime pulls in, and export
# the C ABI via /EXPORT (the Rust symbols aren't __declspec(dllexport), and
# oneCoreSpeech's declspec exports still apply alongside these).
if uwpOcrStaticLib is not None:
	libs += [uwpOcrStaticLib, "ntdll", "userenv", "propsys", "bcrypt"]
	env.Append(
		LINKFLAGS=[
			"/EXPORT:uwpOcr_initialize",
			"/EXPORT:uwpOcr_terminate",
			"/EXPORT:uwpOcr_recognize",
			"/EXPORT:uwpOcr_getLanguages",
		],
	)

localWin10Lib = env.SharedLibrary(
	target="nvdaHelperLocalWin10",
	source=source,
	LIBS=libs,
)

Return(["localWin10Lib"])
