[package]
name = "nvda_ole"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"

[dependencies.windows-core]
version = "0.58"

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Ole",
    "Win32_System_Memory",
]
