[package]
name = "nvda_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "nvdaRust"
crate-type = ["cdylib"]

[dependencies]
nvda_crashdump = { path = "../nvda_crashdump" }
nvda_ole = { path = "../nvda_ole" }
nvda_text = { path = "../nvda_text" }
nvda_tones = { path = "../nvda_tones" }
nvda_wasapi = { path = "../nvda_wasapi" }
pyo3 = { version = "0.28", features = ["extension-module"] }

[dependencies.windows]
version = "0.58"
features = [
    "Win32_Media_Audio",
]
